### ISSUE TITLE
Related Field Referencing in Meilisync?

### ISSUE THREAD

**Issue by zebra-f** [long2ice/meilisync#21]
I couldn't find anything in the documentation mentioning this feature, but it would be nice if meilisync could reference related fields (foreign keys in MySQL and PostgreSQL)
  
Here's an example of how it could work:  
```
    fields:
      id:
      title:
      user__username: username
 ```
or 
```
    fields:
      id:
      title:
      user: 
        username:
```
Edit:
Now that I think about it; the tricky part would be dealing with updates to related fields.
